spring:
  application:
    name: bcngroup
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:~/bcncgroup
    password: ''
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
